# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c96b2e16289b2e9d1546d515923ecb90c53c8e41e39f99543ed779bd1584b3d1f19e7013b03c057616d693902081a6dff1ef848eb17117e53e92ecf53796f05

test:
  secret_key_base: 10e9a9c960809d5d0339b32ee9e6a9767e3208325cc0bf643ccedf21745439eb30f6fe6f05adc5cef071f78ca67beb365776408cc4651245fcaaf7643fc22cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
